import { notoSansJP, finalFantasy, optima } from "@/lib/fonts";
import "./globals.scss";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${notoSansJP.variable} ${finalFantasy.variable} ${optima.variable}`}>
        {children}
      </body>
    </html>
  );
}
